// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: diskside.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileType int32

const (
	FileType_FILE      FileType = 0
	FileType_DIRECTORY FileType = 1
	FileType_SYMLINK   FileType = 2
)

// Enum value maps for FileType.
var (
	FileType_name = map[int32]string{
		0: "FILE",
		1: "DIRECTORY",
		2: "SYMLINK",
	}
	FileType_value = map[string]int32{
		"FILE":      0,
		"DIRECTORY": 1,
		"SYMLINK":   2,
	}
)

func (x FileType) Enum() *FileType {
	p := new(FileType)
	*p = x
	return p
}

func (x FileType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FileType) Descriptor() protoreflect.EnumDescriptor {
	return file_diskside_proto_enumTypes[0].Descriptor()
}

func (FileType) Type() protoreflect.EnumType {
	return &file_diskside_proto_enumTypes[0]
}

func (x FileType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FileType.Descriptor instead.
func (FileType) EnumDescriptor() ([]byte, []int) {
	return file_diskside_proto_rawDescGZIP(), []int{0}
}

type MessageType int32

const (
	MessageType_PAIR_REQUEST          MessageType = 0
	MessageType_PAIR_RESPONSE         MessageType = 1
	MessageType_CONNECT_REQUEST       MessageType = 2
	MessageType_CONNECT_RESPONSE      MessageType = 3
	MessageType_STAT_REQUEST          MessageType = 4
	MessageType_STAT_RESPONSE         MessageType = 5
	MessageType_READDIR_REQUEST       MessageType = 6
	MessageType_READDIR_RESPONSE      MessageType = 7
	MessageType_MKDIR_REQUEST         MessageType = 8
	MessageType_MKDIR_RESPONSE        MessageType = 9
	MessageType_MKNOD_REQUEST         MessageType = 10
	MessageType_MKNOD_RESPONSE        MessageType = 11
	MessageType_RENAME_REQUEST        MessageType = 12
	MessageType_RENAME_RESPONSE       MessageType = 13
	MessageType_DELETE_REQUEST        MessageType = 14
	MessageType_DELETE_RESPONSE       MessageType = 15
	MessageType_BLOCK_EXISTS_REQUEST  MessageType = 16
	MessageType_BLOCK_EXISTS_RESPONSE MessageType = 17
	MessageType_BLOCK_READ_REQUEST    MessageType = 18
	MessageType_BLOCK_READ_RESPONSE   MessageType = 19
	MessageType_BLOCK_WRITE_REQUEST   MessageType = 20
	MessageType_BLOCK_WRITE_RESPONSE  MessageType = 21
	MessageType_INVALIDATE            MessageType = 22
	MessageType_SET_SIZE_REQUEST      MessageType = 23
	MessageType_SET_SIZE_RESPONSE     MessageType = 24
	MessageType_TUNNEL_OPEN_REQUEST   MessageType = 25
	MessageType_TUNNEL_OPEN_RESPONSE  MessageType = 26
	MessageType_TUNNEL_DATA           MessageType = 27
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0:  "PAIR_REQUEST",
		1:  "PAIR_RESPONSE",
		2:  "CONNECT_REQUEST",
		3:  "CONNECT_RESPONSE",
		4:  "STAT_REQUEST",
		5:  "STAT_RESPONSE",
		6:  "READDIR_REQUEST",
		7:  "READDIR_RESPONSE",
		8:  "MKDIR_REQUEST",
		9:  "MKDIR_RESPONSE",
		10: "MKNOD_REQUEST",
		11: "MKNOD_RESPONSE",
		12: "RENAME_REQUEST",
		13: "RENAME_RESPONSE",
		14: "DELETE_REQUEST",
		15: "DELETE_RESPONSE",
		16: "BLOCK_EXISTS_REQUEST",
		17: "BLOCK_EXISTS_RESPONSE",
		18: "BLOCK_READ_REQUEST",
		19: "BLOCK_READ_RESPONSE",
		20: "BLOCK_WRITE_REQUEST",
		21: "BLOCK_WRITE_RESPONSE",
		22: "INVALIDATE",
		23: "SET_SIZE_REQUEST",
		24: "SET_SIZE_RESPONSE",
		25: "TUNNEL_OPEN_REQUEST",
		26: "TUNNEL_OPEN_RESPONSE",
		27: "TUNNEL_DATA",
	}
	MessageType_value = map[string]int32{
		"PAIR_REQUEST":          0,
		"PAIR_RESPONSE":         1,
		"CONNECT_REQUEST":       2,
		"CONNECT_RESPONSE":      3,
		"STAT_REQUEST":          4,
		"STAT_RESPONSE":         5,
		"READDIR_REQUEST":       6,
		"READDIR_RESPONSE":      7,
		"MKDIR_REQUEST":         8,
		"MKDIR_RESPONSE":        9,
		"MKNOD_REQUEST":         10,
		"MKNOD_RESPONSE":        11,
		"RENAME_REQUEST":        12,
		"RENAME_RESPONSE":       13,
		"DELETE_REQUEST":        14,
		"DELETE_RESPONSE":       15,
		"BLOCK_EXISTS_REQUEST":  16,
		"BLOCK_EXISTS_RESPONSE": 17,
		"BLOCK_READ_REQUEST":    18,
		"BLOCK_READ_RESPONSE":   19,
		"BLOCK_WRITE_REQUEST":   20,
		"BLOCK_WRITE_RESPONSE":  21,
		"INVALIDATE":            22,
		"SET_SIZE_REQUEST":      23,
		"SET_SIZE_RESPONSE":     24,
		"TUNNEL_OPEN_REQUEST":   25,
		"TUNNEL_OPEN_RESPONSE":  26,
		"TUNNEL_DATA":           27,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_diskside_proto_enumTypes[1].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_diskside_proto_enumTypes[1]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_diskside_proto_rawDescGZIP(), []int{1}
}

type PairRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PairRequest) Reset() {
	*x = PairRequest{}
	mi := &file_diskside_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PairRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PairRequest) ProtoMessage() {}

func (x *PairRequest) ProtoReflect() protoreflect.Message {
	mi := &file_diskside_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PairRequest.ProtoReflect.Descriptor instead.
func (*PairRequest) Descriptor() ([]byte, []int) {
	return file_diskside_proto_rawDescGZIP(), []int{0}
}

func (x *PairRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type PairResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	JwtToken        string                 `protobuf:"bytes,1,opt,name=jwt_token,json=jwtToken,proto3" json:"jwt_token,omitempty"`
	ServerName      string                 `protobuf:"bytes,2,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	CertFingerprint string                 `protobuf:"bytes,3,opt,name=cert_fingerprint,json=certFingerprint,proto3" json:"cert_fingerprint,omitempty"` // SHA-256 hex of server TLS cert, for pinning
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PairResponse) Reset() {
	*x = PairResponse{}
	mi := &file_diskside_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PairResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PairResponse) ProtoMessage() {}

func (x *PairResponse) ProtoReflect() protoreflect.Message {
	mi := &file_diskside_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PairResponse.ProtoReflect.Descriptor instead.
func (*PairResponse) Descriptor() ([]byte, []int) {
	return file_diskside_proto_rawDescGZIP(), []int{1}
}

func (x *PairResponse) GetJwtToken() string {
	if x != nil {
		return x.JwtToken
	}
	return ""
}

func (x *PairResponse) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *PairResponse) GetCertFingerprint() string {
	if x != nil {
		return x.CertFingerprint
	}
	return ""
}

type TunnelOpenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TunnelOpenRequest) Reset() {
	*x = TunnelOpenRequest{}
	mi := &file_diskside_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TunnelOpenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelOpenRequest) ProtoMessage() {}

func (x *TunnelOpenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_diskside_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelOpenRequest.ProtoReflect.Descriptor instead.
func (*TunnelOpenRequest) Descriptor() ([]byte, []int) {
	return file_diskside_proto_rawDescGZIP(), []int{2}
}

type TunnelOpenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TunnelOpenResponse) Reset() {
	*x = TunnelOpenResponse{}
	mi := &file_diskside_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TunnelOpenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelOpenResponse) ProtoMessage() {}

func (x *TunnelOpenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_diskside_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelOpenResponse.ProtoReflect.Descriptor instead.
func (*TunnelOpenResponse) Descriptor() ([]byte, []int) {
	return file_diskside_proto_rawDescGZIP(), []int{3}
}

func (x *TunnelOpenResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *TunnelOpenResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type TunnelData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"` // raw SMB bytes, bidirectional
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TunnelData) Reset() {
	*x = TunnelData{}
	mi := &file_diskside_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TunnelData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelData) ProtoMessage() {}

func (x *TunnelData) ProtoReflect() protoreflect.Message {
	mi := &file_diskside_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelData.ProtoReflect.Descriptor instead.
func (*TunnelData) Descriptor() ([]byte, []int) {
	return file_diskside_proto_rawDescGZIP(), []int{4}
}

func (x *TunnelData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ConnectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JwtToken      string                 `protobuf:"bytes,1,opt,name=jwt_token,json=jwtToken,proto3" json:"jwt_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectRequest) Reset() {
	*x = ConnectRequest{}
	mi := &file_diskside_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectRequest) ProtoMessage() {}

func (x *ConnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_diskside_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectRequest.ProtoReflect.Descriptor instead.
func (*ConnectRequest) Descriptor() ([]byte, []int) {
	return file_diskside_proto_rawDescGZIP(), []int{5}
}

func (x *ConnectRequest) GetJwtToken() string {
	if x != nil {
		return x.JwtToken
	}
	return ""
}

type ConnectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectResponse) Reset() {
	*x = ConnectResponse{}
	mi := &file_diskside_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectResponse) ProtoMessage() {}

func (x *ConnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_diskside_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectResponse.ProtoReflect.Descriptor instead.
func (*ConnectResponse) Descriptor() ([]byte, []int) {
	return file_diskside_proto_rawDescGZIP(), []int{6}
}

func (x *ConnectResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ConnectResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type DirEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          FileType               `protobuf:"varint,2,opt,name=type,proto3,enum=diskwave.FileType" json:"type,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Mtime         int64                  `protobuf:"varint,4,opt,name=mtime,proto3" json:"mtime,omitempty"`
	Mode          uint32                 `protobuf:"varint,5,opt,name=mode,proto3" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DirEntry) Reset() {
	*x = DirEntry{}
	mi := &file_diskside_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirEntry) ProtoMessage() {}

func (x *DirEntry) ProtoReflect() protoreflect.Message {
	mi := &file_diskside_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirEntry.ProtoReflect.Descriptor instead.
func (*DirEntry) Descriptor() ([]byte, []int) {
	return file_diskside_proto_rawDescGZIP(), []int{7}
}

func (x *DirEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DirEntry) GetType() FileType {
	if x != nil {
		return x.Type
	}
	return FileType_FILE
}

func (x *DirEntry) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *DirEntry) GetMtime() int64 {
	if x != nil {
		return x.Mtime
	}
	return 0
}

func (x *DirEntry) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

type StatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatRequest) Reset() {
	*x = StatRequest{}
	mi := &file_diskside_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatRequest) ProtoMessage() {}

func (x *StatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_diskside_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatRequest.ProtoReflect.Descriptor instead.
func (*StatRequest) Descriptor() ([]byte, []int) {
	return file_diskside_proto_rawDescGZIP(), []int{8}
}

func (x *StatRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type StatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entry         *DirEntry              `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatResponse) Reset() {
	*x = StatResponse{}
	mi := &file_diskside_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatResponse) ProtoMessage() {}

func (x *StatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_diskside_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatResponse.ProtoReflect.Descriptor instead.
func (*StatResponse) Descriptor() ([]byte, []int) {
	return file_diskside_proto_rawDescGZIP(), []int{9}
}

func (x *StatResponse) GetEntry() *DirEntry {
	if x != nil {
		return x.Entry
	}
	return nil
}

func (x *StatResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ReadDirRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadDirRequest) Reset() {
	*x = ReadDirRequest{}
	mi := &file_diskside_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadDirRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadDirRequest) ProtoMessage() {}

func (x *ReadDirRequest) ProtoReflect() protoreflect.Message {
	mi := &file_diskside_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadDirRequest.ProtoReflect.Descriptor instead.
func (*ReadDirRequest) Descriptor() ([]byte, []int) {
	return file_diskside_proto_rawDescGZIP(), []int{10}
}

func (x *ReadDirRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ReadDirResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*DirEntry            `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadDirResponse) Reset() {
	*x = ReadDirResponse{}
	mi := &file_diskside_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadDirResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadDirResponse) ProtoMessage() {}

func (x *ReadDirResponse) ProtoReflect() protoreflect.Message {
	mi := &file_diskside_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadDirResponse.ProtoReflect.Descriptor instead.
func (*ReadDirResponse) Descriptor() ([]byte, []int) {
	return file_diskside_proto_rawDescGZIP(), []int{11}
}

func (x *ReadDirResponse) GetEntries() []*DirEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *ReadDirResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type MkdirRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Mode          uint32                 `protobuf:"varint,2,opt,name=mode,proto3" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MkdirRequest) Reset() {
	*x = MkdirRequest{}
	mi := &file_diskside_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MkdirRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MkdirRequest) ProtoMessage() {}

func (x *MkdirRequest) ProtoReflect() protoreflect.Message {
	mi := &file_diskside_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MkdirRequest.ProtoReflect.Descriptor instead.
func (*MkdirRequest) Descriptor() ([]byte, []int) {
	return file_diskside_proto_rawDescGZIP(), []int{12}
}

func (x *MkdirRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *MkdirRequest) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

type MkdirResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MkdirResponse) Reset() {
	*x = MkdirResponse{}
	mi := &file_diskside_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MkdirResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MkdirResponse) ProtoMessage() {}

func (x *MkdirResponse) ProtoReflect() protoreflect.Message {
	mi := &file_diskside_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MkdirResponse.ProtoReflect.Descriptor instead.
func (*MkdirResponse) Descriptor() ([]byte, []int) {
	return file_diskside_proto_rawDescGZIP(), []int{13}
}

func (x *MkdirResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type MknodRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Mode          uint32                 `protobuf:"varint,2,opt,name=mode,proto3" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MknodRequest) Reset() {
	*x = MknodRequest{}
	mi := &file_diskside_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MknodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MknodRequest) ProtoMessage() {}

func (x *MknodRequest) ProtoReflect() protoreflect.Message {
	mi := &file_diskside_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MknodRequest.ProtoReflect.Descriptor instead.
func (*MknodRequest) Descriptor() ([]byte, []int) {
	return file_diskside_proto_rawDescGZIP(), []int{14}
}

func (x *MknodRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *MknodRequest) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

type MknodResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MknodResponse) Reset() {
	*x = MknodResponse{}
	mi := &file_diskside_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MknodResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MknodResponse) ProtoMessage() {}

func (x *MknodResponse) ProtoReflect() protoreflect.Message {
	mi := &file_diskside_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MknodResponse.ProtoReflect.Descriptor instead.
func (*MknodResponse) Descriptor() ([]byte, []int) {
	return file_diskside_proto_rawDescGZIP(), []int{15}
}

func (x *MknodResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type RenameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OldPath       string                 `protobuf:"bytes,1,opt,name=old_path,json=oldPath,proto3" json:"old_path,omitempty"`
	NewPath       string                 `protobuf:"bytes,2,opt,name=new_path,json=newPath,proto3" json:"new_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenameRequest) Reset() {
	*x = RenameRequest{}
	mi := &file_diskside_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameRequest) ProtoMessage() {}

func (x *RenameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_diskside_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameRequest.ProtoReflect.Descriptor instead.
func (*RenameRequest) Descriptor() ([]byte, []int) {
	return file_diskside_proto_rawDescGZIP(), []int{16}
}

func (x *RenameRequest) GetOldPath() string {
	if x != nil {
		return x.OldPath
	}
	return ""
}

func (x *RenameRequest) GetNewPath() string {
	if x != nil {
		return x.NewPath
	}
	return ""
}

type RenameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenameResponse) Reset() {
	*x = RenameResponse{}
	mi := &file_diskside_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameResponse) ProtoMessage() {}

func (x *RenameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_diskside_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameResponse.ProtoReflect.Descriptor instead.
func (*RenameResponse) Descriptor() ([]byte, []int) {
	return file_diskside_proto_rawDescGZIP(), []int{17}
}

func (x *RenameResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_diskside_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_diskside_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_diskside_proto_rawDescGZIP(), []int{18}
}

func (x *DeleteRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_diskside_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_diskside_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_diskside_proto_rawDescGZIP(), []int{19}
}

func (x *DeleteResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type SetSizeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetSizeRequest) Reset() {
	*x = SetSizeRequest{}
	mi := &file_diskside_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSizeRequest) ProtoMessage() {}

func (x *SetSizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_diskside_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSizeRequest.ProtoReflect.Descriptor instead.
func (*SetSizeRequest) Descriptor() ([]byte, []int) {
	return file_diskside_proto_rawDescGZIP(), []int{20}
}

func (x *SetSizeRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *SetSizeRequest) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type SetSizeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetSizeResponse) Reset() {
	*x = SetSizeResponse{}
	mi := &file_diskside_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetSizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSizeResponse) ProtoMessage() {}

func (x *SetSizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_diskside_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSizeResponse.ProtoReflect.Descriptor instead.
func (*SetSizeResponse) Descriptor() ([]byte, []int) {
	return file_diskside_proto_rawDescGZIP(), []int{21}
}

func (x *SetSizeResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type BlockExistsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockExistsRequest) Reset() {
	*x = BlockExistsRequest{}
	mi := &file_diskside_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockExistsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockExistsRequest) ProtoMessage() {}

func (x *BlockExistsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_diskside_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockExistsRequest.ProtoReflect.Descriptor instead.
func (*BlockExistsRequest) Descriptor() ([]byte, []int) {
	return file_diskside_proto_rawDescGZIP(), []int{22}
}

func (x *BlockExistsRequest) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

type BlockExistsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockExistsResponse) Reset() {
	*x = BlockExistsResponse{}
	mi := &file_diskside_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockExistsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockExistsResponse) ProtoMessage() {}

func (x *BlockExistsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_diskside_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockExistsResponse.ProtoReflect.Descriptor instead.
func (*BlockExistsResponse) Descriptor() ([]byte, []int) {
	return file_diskside_proto_rawDescGZIP(), []int{23}
}

func (x *BlockExistsResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

type BlockReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockReadRequest) Reset() {
	*x = BlockReadRequest{}
	mi := &file_diskside_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockReadRequest) ProtoMessage() {}

func (x *BlockReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_diskside_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockReadRequest.ProtoReflect.Descriptor instead.
func (*BlockReadRequest) Descriptor() ([]byte, []int) {
	return file_diskside_proto_rawDescGZIP(), []int{24}
}

func (x *BlockReadRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *BlockReadRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *BlockReadRequest) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type BlockReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockReadResponse) Reset() {
	*x = BlockReadResponse{}
	mi := &file_diskside_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockReadResponse) ProtoMessage() {}

func (x *BlockReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_diskside_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockReadResponse.ProtoReflect.Descriptor instead.
func (*BlockReadResponse) Descriptor() ([]byte, []int) {
	return file_diskside_proto_rawDescGZIP(), []int{25}
}

func (x *BlockReadResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *BlockReadResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type BlockWriteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockWriteRequest) Reset() {
	*x = BlockWriteRequest{}
	mi := &file_diskside_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockWriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockWriteRequest) ProtoMessage() {}

func (x *BlockWriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_diskside_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockWriteRequest.ProtoReflect.Descriptor instead.
func (*BlockWriteRequest) Descriptor() ([]byte, []int) {
	return file_diskside_proto_rawDescGZIP(), []int{26}
}

func (x *BlockWriteRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *BlockWriteRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *BlockWriteRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type BlockWriteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Written       int64                  `protobuf:"varint,1,opt,name=written,proto3" json:"written,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockWriteResponse) Reset() {
	*x = BlockWriteResponse{}
	mi := &file_diskside_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockWriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockWriteResponse) ProtoMessage() {}

func (x *BlockWriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_diskside_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockWriteResponse.ProtoReflect.Descriptor instead.
func (*BlockWriteResponse) Descriptor() ([]byte, []int) {
	return file_diskside_proto_rawDescGZIP(), []int{27}
}

func (x *BlockWriteResponse) GetWritten() int64 {
	if x != nil {
		return x.Written
	}
	return 0
}

func (x *BlockWriteResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type InvalidateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvalidateRequest) Reset() {
	*x = InvalidateRequest{}
	mi := &file_diskside_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvalidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvalidateRequest) ProtoMessage() {}

func (x *InvalidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_diskside_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvalidateRequest.ProtoReflect.Descriptor instead.
func (*InvalidateRequest) Descriptor() ([]byte, []int) {
	return file_diskside_proto_rawDescGZIP(), []int{28}
}

func (x *InvalidateRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type Envelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     uint32                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Type          MessageType            `protobuf:"varint,2,opt,name=type,proto3,enum=diskwave.MessageType" json:"type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_diskside_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_diskside_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_diskside_proto_rawDescGZIP(), []int{29}
}

func (x *Envelope) GetRequestId() uint32 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *Envelope) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_PAIR_REQUEST
}

func (x *Envelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_diskside_proto protoreflect.FileDescriptor

const file_diskside_proto_rawDesc = "" +
	"\n" +
	"\x0ediskside.proto\x12\bdiskwave\"!\n" +
	"\vPairRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\"w\n" +
	"\fPairResponse\x12\x1b\n" +
	"\tjwt_token\x18\x01 \x01(\tR\bjwtToken\x12\x1f\n" +
	"\vserver_name\x18\x02 \x01(\tR\n" +
	"serverName\x12)\n" +
	"\x10cert_fingerprint\x18\x03 \x01(\tR\x0fcertFingerprint\"\x13\n" +
	"\x11TunnelOpenRequest\":\n" +
	"\x12TunnelOpenResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\" \n" +
	"\n" +
	"TunnelData\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"-\n" +
	"\x0eConnectRequest\x12\x1b\n" +
	"\tjwt_token\x18\x01 \x01(\tR\bjwtToken\"7\n" +
	"\x0fConnectResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x84\x01\n" +
	"\bDirEntry\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12&\n" +
	"\x04type\x18\x02 \x01(\x0e2\x12.diskwave.FileTypeR\x04type\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x12\x14\n" +
	"\x05mtime\x18\x04 \x01(\x03R\x05mtime\x12\x12\n" +
	"\x04mode\x18\x05 \x01(\rR\x04mode\"!\n" +
	"\vStatRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"N\n" +
	"\fStatResponse\x12(\n" +
	"\x05entry\x18\x01 \x01(\v2\x12.diskwave.DirEntryR\x05entry\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"$\n" +
	"\x0eReadDirRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"U\n" +
	"\x0fReadDirResponse\x12,\n" +
	"\aentries\x18\x01 \x03(\v2\x12.diskwave.DirEntryR\aentries\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"6\n" +
	"\fMkdirRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\rR\x04mode\"%\n" +
	"\rMkdirResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"6\n" +
	"\fMknodRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\rR\x04mode\"%\n" +
	"\rMknodResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"E\n" +
	"\rRenameRequest\x12\x19\n" +
	"\bold_path\x18\x01 \x01(\tR\aoldPath\x12\x19\n" +
	"\bnew_path\x18\x02 \x01(\tR\anewPath\"&\n" +
	"\x0eRenameResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"#\n" +
	"\rDeleteRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"&\n" +
	"\x0eDeleteResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"8\n" +
	"\x0eSetSizeRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\"'\n" +
	"\x0fSetSizeResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"(\n" +
	"\x12BlockExistsRequest\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\"-\n" +
	"\x13BlockExistsResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists\"R\n" +
	"\x10BlockReadRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\"=\n" +
	"\x11BlockReadResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"S\n" +
	"\x11BlockWriteRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"D\n" +
	"\x12BlockWriteResponse\x12\x18\n" +
	"\awritten\x18\x01 \x01(\x03R\awritten\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"'\n" +
	"\x11InvalidateRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"n\n" +
	"\bEnvelope\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\rR\trequestId\x12)\n" +
	"\x04type\x18\x02 \x01(\x0e2\x15.diskwave.MessageTypeR\x04type\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload*0\n" +
	"\bFileType\x12\b\n" +
	"\x04FILE\x10\x00\x12\r\n" +
	"\tDIRECTORY\x10\x01\x12\v\n" +
	"\aSYMLINK\x10\x02*\xe7\x04\n" +
	"\vMessageType\x12\x10\n" +
	"\fPAIR_REQUEST\x10\x00\x12\x11\n" +
	"\rPAIR_RESPONSE\x10\x01\x12\x13\n" +
	"\x0fCONNECT_REQUEST\x10\x02\x12\x14\n" +
	"\x10CONNECT_RESPONSE\x10\x03\x12\x10\n" +
	"\fSTAT_REQUEST\x10\x04\x12\x11\n" +
	"\rSTAT_RESPONSE\x10\x05\x12\x13\n" +
	"\x0fREADDIR_REQUEST\x10\x06\x12\x14\n" +
	"\x10READDIR_RESPONSE\x10\a\x12\x11\n" +
	"\rMKDIR_REQUEST\x10\b\x12\x12\n" +
	"\x0eMKDIR_RESPONSE\x10\t\x12\x11\n" +
	"\rMKNOD_REQUEST\x10\n" +
	"\x12\x12\n" +
	"\x0eMKNOD_RESPONSE\x10\v\x12\x12\n" +
	"\x0eRENAME_REQUEST\x10\f\x12\x13\n" +
	"\x0fRENAME_RESPONSE\x10\r\x12\x12\n" +
	"\x0eDELETE_REQUEST\x10\x0e\x12\x13\n" +
	"\x0fDELETE_RESPONSE\x10\x0f\x12\x18\n" +
	"\x14BLOCK_EXISTS_REQUEST\x10\x10\x12\x19\n" +
	"\x15BLOCK_EXISTS_RESPONSE\x10\x11\x12\x16\n" +
	"\x12BLOCK_READ_REQUEST\x10\x12\x12\x17\n" +
	"\x13BLOCK_READ_RESPONSE\x10\x13\x12\x17\n" +
	"\x13BLOCK_WRITE_REQUEST\x10\x14\x12\x18\n" +
	"\x14BLOCK_WRITE_RESPONSE\x10\x15\x12\x0e\n" +
	"\n" +
	"INVALIDATE\x10\x16\x12\x14\n" +
	"\x10SET_SIZE_REQUEST\x10\x17\x12\x15\n" +
	"\x11SET_SIZE_RESPONSE\x10\x18\x12\x17\n" +
	"\x13TUNNEL_OPEN_REQUEST\x10\x19\x12\x18\n" +
	"\x14TUNNEL_OPEN_RESPONSE\x10\x1a\x12\x0f\n" +
	"\vTUNNEL_DATA\x10\x1bB+Z)github.com/diskwave/server/internal/protob\x06proto3"

var (
	file_diskside_proto_rawDescOnce sync.Once
	file_diskside_proto_rawDescData []byte
)

func file_diskside_proto_rawDescGZIP() []byte {
	file_diskside_proto_rawDescOnce.Do(func() {
		file_diskside_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_diskside_proto_rawDesc), len(file_diskside_proto_rawDesc)))
	})
	return file_diskside_proto_rawDescData
}

var file_diskside_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_diskside_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_diskside_proto_goTypes = []any{
	(FileType)(0),               // 0: diskwave.FileType
	(MessageType)(0),            // 1: diskwave.MessageType
	(*PairRequest)(nil),         // 2: diskwave.PairRequest
	(*PairResponse)(nil),        // 3: diskwave.PairResponse
	(*TunnelOpenRequest)(nil),   // 4: diskwave.TunnelOpenRequest
	(*TunnelOpenResponse)(nil),  // 5: diskwave.TunnelOpenResponse
	(*TunnelData)(nil),          // 6: diskwave.TunnelData
	(*ConnectRequest)(nil),      // 7: diskwave.ConnectRequest
	(*ConnectResponse)(nil),     // 8: diskwave.ConnectResponse
	(*DirEntry)(nil),            // 9: diskwave.DirEntry
	(*StatRequest)(nil),         // 10: diskwave.StatRequest
	(*StatResponse)(nil),        // 11: diskwave.StatResponse
	(*ReadDirRequest)(nil),      // 12: diskwave.ReadDirRequest
	(*ReadDirResponse)(nil),     // 13: diskwave.ReadDirResponse
	(*MkdirRequest)(nil),        // 14: diskwave.MkdirRequest
	(*MkdirResponse)(nil),       // 15: diskwave.MkdirResponse
	(*MknodRequest)(nil),        // 16: diskwave.MknodRequest
	(*MknodResponse)(nil),       // 17: diskwave.MknodResponse
	(*RenameRequest)(nil),       // 18: diskwave.RenameRequest
	(*RenameResponse)(nil),      // 19: diskwave.RenameResponse
	(*DeleteRequest)(nil),       // 20: diskwave.DeleteRequest
	(*DeleteResponse)(nil),      // 21: diskwave.DeleteResponse
	(*SetSizeRequest)(nil),      // 22: diskwave.SetSizeRequest
	(*SetSizeResponse)(nil),     // 23: diskwave.SetSizeResponse
	(*BlockExistsRequest)(nil),  // 24: diskwave.BlockExistsRequest
	(*BlockExistsResponse)(nil), // 25: diskwave.BlockExistsResponse
	(*BlockReadRequest)(nil),    // 26: diskwave.BlockReadRequest
	(*BlockReadResponse)(nil),   // 27: diskwave.BlockReadResponse
	(*BlockWriteRequest)(nil),   // 28: diskwave.BlockWriteRequest
	(*BlockWriteResponse)(nil),  // 29: diskwave.BlockWriteResponse
	(*InvalidateRequest)(nil),   // 30: diskwave.InvalidateRequest
	(*Envelope)(nil),            // 31: diskwave.Envelope
}
var file_diskside_proto_depIdxs = []int32{
	0, // 0: diskwave.DirEntry.type:type_name -> diskwave.FileType
	9, // 1: diskwave.StatResponse.entry:type_name -> diskwave.DirEntry
	9, // 2: diskwave.ReadDirResponse.entries:type_name -> diskwave.DirEntry
	1, // 3: diskwave.Envelope.type:type_name -> diskwave.MessageType
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_diskside_proto_init() }
func file_diskside_proto_init() {
	if File_diskside_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_diskside_proto_rawDesc), len(file_diskside_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_diskside_proto_goTypes,
		DependencyIndexes: file_diskside_proto_depIdxs,
		EnumInfos:         file_diskside_proto_enumTypes,
		MessageInfos:      file_diskside_proto_msgTypes,
	}.Build()
	File_diskside_proto = out.File
	file_diskside_proto_goTypes = nil
	file_diskside_proto_depIdxs = nil
}
